# Supabase credentials
[supabase]
url = "https://rqgmobpywjmvdofysqjq.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJxZ21vYnB5d2ptdmRvZnlzcWpxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQwOTc4NzQsImV4cCI6MjA3OTY3Mzg3NH0.JGx9eq1zSlYrFHq5P1EYH98GRwpn45IFda__6FtHtvA"

[garmin]
email = "tylketchum@gmail.com"
password = "Newman5504"
